name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        name: Checkout do repositório
      - name: Autenticação no Docker
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Construção da imagem Docker
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            helioneto94/devops4devs-news:latest
            helioneto94/devops4devs-news:${{github.run_number}}

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Conectar com o Kubernetes
        run: echo "Configuração do Kubeconfig"
      - name: Executar Deploy
        run: echo "Kubectl apply"
    
